language: racket

env:
 - RACKET_VERSION=5.3.5

before_install:
 - chmod u+rx ./install-racket.sh
 - ./install-racket.sh

install:

before_script:

script:
 - /usr/racket/bin/raco make main.rkt
 - /usr/racket/bin/raco test -x .

after_script:
