language: c

# Optional: To use Travis CI's newer container infrastucture,
# un-comment the following line, AND ALSO be sure RACKET_DIR is set to
# ~/racket (or somewhere else that doesn't require sudo to install
# Racket there).
#
# sudo: false

# 1. Supply at least one RACKET_VERSION environment variable
#    definition here. RACKET_VERSION is used by the install-racket.sh
#    script (specifed below under before_install) to select the
#    version of Racket to download and install.
#
#    If you supply more than one, you can create multiple builds (a
#    Travis-CI build matrix resulting in multiple builds). You can use
#    this to test against multiple Racket versions.
#
# 2. Supply one RACKET_DIR environment variable definition here. This
#    is where Racket will be installed. If you omit this, it defaults
#    to /usr/racket. However note that this default is incompatible
#    with using Travis CI's container infrastructure. If you enable
#    that (by setting `sudo: false` above), then you should set
#    RACKET_DIR to a location that doesn't require sudo: A good
#    idea is to use ~/racket.
env:
  - RACKET_VERSION=5.3.4
  - RACKET_VERSION=5.3.5
  - RACKET_VERSION=5.92
  - RACKET_VERSION=6.0
  - RACKET_VERSION=6.1
  - RACKET_VERSION=6.1.1
  - RACKET_VERSION=HEAD
  - RACKET_DIR=~/racket

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cd travis-racket              ### JUST FOR TESTING, DON'T MERGE TO MASTER
  - git checkout travis-container ### JUST FOR TESTING, DON'T MERGE TO MASTER
  - cd ..                         ### JUST FOR TESTING, DON'T MERGE TO MASTER
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

install:

before_script:

# Here supply steps such as raco make, raco test, etc.
#
# Tip: Use `raco pkg install --deps search-auto <pkg>` to install any
# required packages without getting stuck on a confirmation prompt.
script:
  - echo $PATH
  - raco make main.rkt
  - raco test -x .

# NOTE: If your repo is a Racket package with an info.rkt that
# includes some `deps`, the following is more elegant:
#
# script:
# - cd ..   # Travis did a cd into the dir. Back up, for the next:
# - /usr/racket/bin/raco pkg install --deps search-auto --link <pkg>
# - /usr/racket/bin/raco test -x -p <pkg>

after_script:
